name: CI

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6 # or alternative dependency management
    - name: Setup PHP with Xdebug
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: xdebug
    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
        php artisan key:generate
        mkdir coverage-report

    - name: Run Testsuite
      run: php artisan test --coverage --coverage-html=coverage-report --coverage-text=coverage.txt --log-junit results.xml --testdox-html results.html 
  
    - name: Archive code Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: results
        path: |
          results.xml
          results.html 

    - name: Archive code coverage results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: |
          coverage.txt
          coverage-report


    # - uses: php-actions/phpunit@v3
    # ... then your own project steps ...