name: "Build LaTeX Report"

on: [push]

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
    - name: "Build Latex Report"
      uses: xu-cheng/latex-action@v3
      with:
        root_file: "report/Project%20Report.tex"